export default [
  'Renal biopsy',
  'Nervous system',
  'Eye (part-time)',
  'Eye',
  'KUB (part-time)',
  'KUB (kidney, prostate, bladder)',
  'Adrenal gland',
  'Pediatric tumor',
  'Neuroblastoma',
  'Thyroid + Parathyroid',
  'ENT',
  'Breast 1 (Simple)',
  'Breast (Simple) ที่เหลือ',
  'Breast 2 (Advance)',
  'Breast 3 (Core biopsy)',
  'INTERSEX',
  'Placenta',
  'Gyne 1 (L 1)',
  'Gyne 1 (L 2)',
  'Gyne 2 (MH 1)',
  'Gyne 2 (MH 2)',
  'Gyne 3 (Medium 1)',
  'Gyne 3 (Medium 2)',
  'Gyne 4 (Small 1)',
  'Gyne 4 (Small 2)',
  'Gyne ที่เหลือ',
  'Gyn Non-malignant tumor',
  'Skin (ตจวิทยา)(part-time)',
  'Skin (นอกตจวิทยา)(part-time)',
  'Skin (ตจวิทยา)',
  'Skin (นอกตจวิทยา) ที่เหลือ',
  'LN, Spleen, Hemato, BM (part-time)',
  'LN, Spleen, Hemato, BM',
  'Mediastinum, Thymus',
  'Heart valve, aorta, หลอดเลือด',
  'Lung',
  'Cardiac bx, Transplant',
  'Bone, Soft tissue, ขาเน่า',
  'GI กลาง-ใหญ่',
  'Appendix, GB, Colectomy',
  'GI biopsy',
  'GI กลาง-ใหญ่ ที่เหลือ',
  'Appendix, GB, Colectomy ที่เหลือ',
  'GI biopsy ที่เหลือ',
  'Liver biopsy',
]
